// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fahfkmemswngdueylbdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhaGZrbWVtc3duZ2R1ZXlsYmRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MzY3NzgsImV4cCI6MjA2NjExMjc3OH0.qghISXrJSOmOaOtlomKJ07U15wubM2fZimnuiIdNhXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);